### ISSUE TITLE
Booting ship fails on `linux-aarch64` with `boot: sigsegv install failed`

### ISSUE THREAD

**Issue by mcevoypeter** [urbit/vere#113]
As reported by ~tarnyl-sillyn in the Help channel of the Urbit Community group, running v1.16 of the binary from https://bootstrap.urbit.org/vere/live/v1.16/vere-v1.16-linux-aarch64 results in the following when attempting to boot a ship:
```console
$ ./vere-v1.16-linux-aarch64 nec
~
urbit 1.16
boot: home is /root/code/gh/urbit/vere/nec
boot: sigsegv install failed
```
I suspect this is due to the fact that we're cross compiling for `linux-aarch64` from `linux-x86_64` because native builds of the `linux-aarch64` on my `linux-aarch64` VM do not exhibit this behavior.

**Comment by mcevoypeter** [comment]
Turns out this was caused by misconfiguration of `libsigsegv`. We were passing `--host=aarch64-linux-musl` to `libsigsegv`'s configure script, which worked for native (i.e. building for `linux-aarch64` on `linux-aarch64`) builds, but not for cross compiling from `linux-x86_64` to `linux-aarch64`. The correct options for cross compilation are `--host=x86_64-linux --target=aarch64-linux-musl`.

**Comment by datryn-ribdun** [comment]
Im experiencing this same issue on my rasberry pi moon:

![sigsegv error](https://user-images.githubusercontent.com/104508587/212760807-16704310-89f1-499e-aa8c-e855f24cd83e.png)

Above comment from @mcevoypeter makes it seem like we know that the build script needs a different set of compilations options, but does that mean a new realease will need to happen before my ship can run? Should I just revert to 1.15 temporarily?

**Comment by mcevoypeter** [comment]
After further testing, the cross compilation fix mentioned above (https://github.com/urbit/vere/issues/113#issuecomment-1382580119) does not work. To resolve this issue, enabling native `linux-aarch64` builds and disabling cross compilation seems to be the way to go.
