### ISSUE TITLE
Random characters in version cause errors in boot process

### ISSUE THREAD

**Issue by ixv** [urbit/vere#120]
I built vere for arch linux and it includes some random characters in the version: `urbit 1.17-eedbbdcd0d`
This then causes it to try and download the pill `https://bootstrap.urbit.org/urbit-v1.17-eedbbdcd0d.pill`

```
urbit 1.17-eedbbdcd0d
boot: home is zod
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.17-eedbbdcd0d.pill
curl: error https://bootstrap.urbit.org/urbit-v1.17-eedbbdcd0d.pill: HTTP 403
```

**Comment by mcevoypeter** [comment]
Those characters trailing the `1.17-` are the shortened commit SHA of the commit from which the binary you're running was built. As you've noticed, we don't upload pills tagged with version numbers of this format, but you can get around this by supplying `-u https://bootstrap.urbit.org/urbit-v1.16.pill` to the `urbit` invocation. I've filed #126 to track the documentation of this issue and corresponding work-around.
