### ISSUE TITLE
Strip trailing commit SHA from version number when downloading pill

### ISSUE THREAD

**Issue by mcevoypeter** [urbit/vere#126]
Unless the train (pace) is "live", the shortened commit SHA causes an issue when attempting to download the pill from https://bootstrap.urbit.org/urbit-v{version}.pill. We should document this and the use of `-u` as a work-around in [CONTRIBUTING.md](https://github.com/urbit/vere/tree/develop/CONTRIBUTING.md).

**Comment by mcevoypeter** [comment]
#120 is an example of this issue.

**Comment by philipcmonk** [comment]
IMO when fetching the pill we should just strip out the SHA hash if it's present.
