### ISSUE TITLE
Binary fails to dock on RPi ARM

### ISSUE THREAD

**Issue by sigilante** [urbit/vere#134]
Running 1.15:

```
$ ./bin/urbit dock lagrev-nocfep/
vere: link lagrev-nocfep//.run -> lagrev-nocfep//.bin/live/vere-v1.15-aarch64-linux failed: Operation not permitted
vere: link lagrev-nocfep//.run failed
vere: binary copy failed
Assertion failed: 0 (src/unix/core.c: uv_close: 178)
Aborted
```

**Comment by sigilante** [comment]
Possibly a symlink issue?

**Comment by mcevoypeter** [comment]
Looks like you have a trailing slash on your pier. Can you try `./bin/urbit dock lagrev-nocfep` instead of `./bin/urbit dock lagrev-nocfep/`?

**Comment by sigilante** [comment]
```
$ ./bin/urbit dock lagrev-nocfep
vere: link lagrev-nocfep/.run -> lagrev-nocfep/.bin/live/vere-v1.17-linux-aarch64 failed: Operation not permitted
vere: link lagrev-nocfep/.run failed
vere: binary copy failed
Assertion failed: 0 (src/unix/core.c: uv_close: 190)
Aborted
```

**Comment by mcevoypeter** [comment]
What are the permissions on the pier?

**Comment by sigilante** [comment]
```
drwxr-xr-x 10 pi pi 131072 Jan 19 10:55  lagrev-nocfep
```

**Comment by mcevoypeter** [comment]
This error is the result of [`link()` failing](https://github.com/urbit/vere/blob/4e89526eb11cacf237cf2b5198c03527a2f5968b/pkg/vere/king.c#L1118) with `EPERM`. Based on the [man page for `link()`](https://man7.org/linux/man-pages/man2/link.2.html), the reason for this is one of:

- The filesystem containing does not support the creation of hard links.
- The caller does not have permission to create a hard link to this file (see the description of `/proc/sys/fs/protected_hardlinks `in [`proc(5)`](https://man7.org/linux/man-pages/man5/proc.5.html)).
- `lagrev-nocfep/.bin/live/vere-v1.17-linux-aarch64` is marked immutable or append-only.  (See [`ioctl_iflags(2)`](https://man7.org/linux/man-pages/man2/ioctl_iflags.2.html).)

To that end, are you able to create a hard link on your system?

**Comment by sigilante** [comment]
That's it then:  the drive is `exfat` which doesn't support links of any kind.
