### ISSUE TITLE
term: content pushed out of scroll region disappears in some terminals

### ISSUE THREAD

**Issue by Fang-** [urbit/vere#168]
A report from the field, thanks to ~nomryg-nilref:

> After running `-test` and the output exceeds the screen size I can no longer scroll back to earlier output. Only the current screen's output can be viewed, (...) in Gnome's terminal.

> Seems to have something to do with test output. I can say for sure when all tests pass I cannot scroll past one screen's worth of output in Gnome terminal. (...)
> Last time (an hour or 2 ago) I had failing tests I could scroll completely back through all the test output in Gnome terminal. Nothing was wrong with that terminal.

As of vere v1.17, we have changed the way printfs get rendered. Instead of overwriting the line at the bottom of the screen, we use [control sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) to 1) set the scroll region to exclude the bottom line (the prompt), 2) scroll up by one line, 3) draw the printf in the empty space we have created. Step (1) ensures we never clobber the prompt, wrapping text will simply push other content up. (Afterwards, we reset the scroll region, back to the whole screen.)

On all terminals I have personally tested, (1) does not interfere with the backlog scrolling afforded natively by those terminals. Content simply gets pushed up into scrollback as normal. Perhaps, for Gnome's default terminal, this is not the case?

Unclear what can be done about this without changing the whole printf printing approach. The previous implementation stored the bottom line of the screen so that it could be overwritten and reconstructed.

Notably this problem will not exist once we separate out printfs from formal output entirely, by making vere start up in a non-interactive mode by default, and attaching to its terminal sessions using a separate process. See also logging reform.

**Comment by jackfoxy** [comment]
I have the same problem with `http://localhost:8081/apps/webterm/` which is the port I am running my fake zod on.
It's not always exactly only the visible output. Sometimes it will scroll back several more results, and webterm and Gnome will scroll back different amounts. 
There are a couple hundred test results in my test run.
Maybe it is my Linux version, which is NixOS.

**Comment by Fang-** [comment]
Okay, unsure how I missed this the first time, but I can now indeed reproduce this behavior in webterm.

Minimal viable repro is just issuing a printf while content is at the top of the screen, and then observing that if you scroll back up, a line has disappeared from scrollback. If you issue multiple printfs in a row, multiple lines get eaten.

On further investigation, [this helpful site](https://terminalguide.namepad.de/seq/csi_cs/) describes explicitly that the "scroll up" sequence we use ((2) from above) explicitly _removes the top line_ before scrolling the rest of the contents up.

The reason I could not reproduce in other xterm environments (VSCode's terminal) or other terminal emulators is that, all this time, I have been running inside of tmux, completely clueless to the fact that this appears to significantly impact a number of different behaviors.

In hindsight, this was naive. Apologies for the troubles this has caused, I will mull this over and find a more broadly compatible solution. Worst case we can always revert to something closer to the previous implementation, which couples the stack a bit more tightly again, but at least does so at a place we know we want to rip and tear at some point in the near future.
