### ISSUE TITLE
HTTP 403 error for pill v1.18-972f27e044

### ISSUE THREAD

**Issue by bonbud-macryg** [urbit/vere#178]
When I try to boot a fakeship or a comet following `### Boot a New Fake Ship` in the `CONTRIBUTING.md` doc I get the following 403 error:

```
~
urbit 1.18-972f27e044
boot: home is zod
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.18-972f27e044.pill
curl: error https://bootstrap.urbit.org/urbit-v1.18-972f27e044.pill: HTTP 403
```

Worth noting that I and several others saw 403 errors while trying to install the regular `v1.17` release soon after it went out, perhaps this is caused by the same issue?

**Comment by lycurgus** [comment]
Per https://github.com/urbit/vere/issues/120#issuecomment-1387435541 you should pass it the URL of a stable pill to load. On startup by default `vere` requests a pill matching its own version, but non-release builds have their commit hash in the version number (that's the `-972f27e044` part in your version) which means they don't match a published pill.

`-u https://bootstrap.urbit.org/urbit-v1.17.pill` should do it - though I don't know if the 1.17 pill is compatible with the 1.18 runtime. You might need to check out an older commit and build from that?

**Comment by mcevoypeter** [comment]
Related: https://github.com/urbit/vere/pull/133.

**Comment by bonbud-macryg** [comment]
#185 is a more refined/actionable version of this issue; closing this one.
