### ISSUE TITLE
Elastic memory growth

### ISSUE THREAD

**Issue by lukestiles** [urbit/vere#188]
Demand paging was [released in 1.14](https://github.com/urbit/urbit/releases/tag/urbit-v1.14). There was a bug that required [releasing 1.15](https://github.com/urbit/urbit/releases/tag/urbit-v1.15) as a rollback to 1.13.

The relevant PRs need to be pulled into the migrated repo and tested. Good entry points to understand what to include are https://github.com/urbit/urbit/pull/6063 and https://github.com/urbit/urbit/pull/6152.

**Comment by joemfb** [comment]
The memory corruption caused by the implementation from those PRs was tracked in urbit/urbit#6173.

**Comment by mcevoypeter** [comment]
I know we've been using demand paging as the term to describe the feature implemented in v1.14, but the term is confusing. We're not implementing demand paging but taking advantage of the fact that the underlying OS implements demand paging beneath its virtual memory abstraction to add support for elastic memory growth.

**Comment by mcevoypeter** [comment]
Update: we can and should rely on the kernel to handle as much of the memory management and snapshotting for us as possible. Fortunately, `mmap()` and `msync()` when used in conjunction with `libsigsegv` provide us the flexibility we need. The basic idea is to create a shared file-backed mapping for the snapshot when a ship launches, which will remove the need to create a 2GB anonymous memory mapping right up front. For each read/write access in the loom that falls outside the boundary of the mapping backed by the snapshot, we'll lazily `mmap()` additional anonymous mappings. When it comes time to take a snapshot, we'll `msync()` to flush the changes to the file-backed mapping to disk, append any anonymous mappings that also belong in the snapshot, and then re-map the snapshot so we remove as many anonymous mappings as possible.

This approach ensures we request memory from the kernel in an incremental fashion and also gives the kernel a well-defined place on disk to swap pages to, which is vital for ships running in Kubernetes, which doesn't support swap. By using `msync()`, we also get the kernel to do most of the heavy lifting when updating a snapshot. As a result, we'll no longer need the error-prone patching method currently used in `pkg/noun/events.c`. There will also be opportunities to use `madvise()` to help the kernel manage the pages of the loom as efficiently as possible.

After some trial and error, I've settled on the following interface for the above system:
```c
struct pma {
    void *heap_start;

    void *stack_start;

    /// Number of bytes of the heap are mapped into memory. Guaranteed to be a
    /// multiple of kPageSz.
    size_t heap_len;

    /// Number of bytes of the stack mapped into memory. Guaranteed to be a
    /// multiple of kPageSz.
    size_t stack_len;

    int    heap_fd;

    int    stack_fd;

    size_t max_sz;
};
typedef struct pma pma_t;

pma_t *
pma_init(void *base, size_t len, const char *heap_file, const char *stack_file);

int
pma_sync(pma_t *pma, size_t heap_sz, size_t stack_sz);

void
pma_deinit(pma_t *pma);
```
As of today, I've implemented and tested a large portion of the interface. The interface can be used in both the king, which doesn't require snapshotting, as well as the serf, which does, to handle the memory of the loom.

The remaining action items are:
- [ ] Implement `pma_sync()`[^1].
- [ ] Test full implementation.
- [ ] Replace `u3e_*()` call sites (i.e. the existing snapshot implementation) with `pma_*()` (this new implementation).

[^1]: If you're thinking, "He only implemented `pma_init()` and `pma_deinit()`? That's not much." You should know that implementing `pma_init()` to properly map the snapshot and lazily map memory in response to page faults is the lion's share of the work, and that's complete.

**Comment by joemfb** [comment]
How does this design achieve atomicity of snapshot updates? How will you recover from a crash during an update?

**Comment by mcevoypeter** [comment]
You bring up a good point. In the absence of an [atomic `msync()`](https://web.eecs.umich.edu/~tpkelly/papers/Failure_atomic_msync_EuroSys_2013.pdf), your implication that we need a patch-based update mechanism--effectively a journal--seems to be the only way.

**Comment by mcevoypeter** [comment]
The snapshot updating mechanism has been implemented and tested with unit tests. I'm hitting a segfault in the worker when using the new snapshotting implementation for running a fake ship and am actively debugging. Up-to-date code can be seen on branch [i/188](https://github.com/urbit/vere/tree/i/188).

**Comment by philipcmonk** [comment]
@mcevoypeter How familiar are you with this work? https://github.com/ashelkovnykov/pma_malloc
