### ISSUE TITLE
Running the binary against a non-existent pier name creates a new comet instead of complaining

### ISSUE THREAD

**Issue by lycurgus** [urbit/vere#190]
**Describe the bug**
Running `urbit thispierdoesntexist` starts a new comet, instead of complaining and expecting the `-c` flag.

**To Reproduce**
1. run `urbit thispierdoesntexist` (substitute a different pier name if you happen to have a pier with that name :P )
2. observe that the runtime happily boots a new comet

**Expected behaviour**
If the pier isn't found and `-c` (create a new pier) isn't specified, the runtime should throw an error (possibly suggesting the use of `-c` to the user).

**System:**
 - OS: linux64 but also observed on Mac
 - Vere and Urbit OS versions: occurs on all recent vere (from 1.0 to 1.5)

**Additional context**
I've seen a few users run into confusion when they are in the wrong directory, or have moved their pier, and run an older command in an attempt to start up a ship they think should be there. A particular example (which prompted this report) was from a user who migrated their ship into Port:

- normally, run `./urbit sampel-palnet` to start up
- import ship into Port, encounter errors and give up
  - unbeknownst to the user, Port defaults to moving their pier into its own directory to avoid double-booting
- try to go back to using the regular command - but `./urbit sampel-palnet` now boots a comet in the same location because the folder had been removed from its previous spot

Similar things have happened in the absence of Port when e.g. the user installs the binaries and their pier into `~/urbit` and doesn't realise they need to be in that same directory to start back up again later - suddenly `./urbit sampel-palnet` complains about `urbit` being a directory. They do some digging and find that the binary they want is _inside_ that directory, so they run `./urbit/urbit sampel-palnet`, but because they're a directory _up_ from where the pier is, they get a new comet at `~/sampel-palnet` instead of booting `~/urbit/sampel-palnet` as they were intending. (I don't think it's sensible to go as far as searching for pier-shaped directories and asking "did you mean to use \<this other path to a pier\>?" but throwing an error would give the user a clear indication that something was amiss with what they were asking the binary to do).

As it stands these sorts of cases appear to the user like "my planet suddenly turned into a comet and I don't know why".

**Comment by barter-simsum** [comment]
This seems to have been an intentional change ("make -c optional") introduced by @joemfb at some point. Joe, what do you think of requiring `-c` rather than implicitly creating a comet when the pier directory doesn't exist.

https://github.com/urbit/vere/blob/17c14ace3096d6851899c3b8ec7bbbb5a0c1633e/pkg/vere/main.c#L464

https://github.com/urbit/vere/commit/964a86eef34610ba9d1271993875d23c0615fc73

**Comment by zalberico** [comment]
I've seen this behavior confuse users - they try to boot with their patp and don't understand what they're doing, they end up with a directory of a comet named after their patp which is very confusing for them (and us when they ask for help). This is despite it outputting text about booting a comet.

Or they try to use pack but get the command args in the wrong order and it starts a comet instead.

We should error out in this case or at a minimum require a Y/N interaction, but I think erroring is preferred.

**Comment by tacryt-socryp** [comment]
I would far prefer error behavior rather than implicit pier generation

**Comment by barter-simsum** [comment]
I agree. Booting a comet when a pier doesn't exist is strange behavior. But I'd like to know why it was introduced in the first place and if it's being used to prevent something else bad from occurring.

**Comment by joemfb** [comment]
@barter-simsum this behavior long pre-dates me. I think it was part of an early "just boot a comet and play around" onboarding push. `-c` is actually just a boolean flag ("create a new pier"), other things also toggle the same flag (`-w`, for instance). The pier name is an optional positional argument, set to the ship name if unspecified... The command-line arguments need plenty of cleanup -- lots of surprises and strangeness.

**Comment by zalberico** [comment]
Cool - sounds like we're good to fix this. When we do we'll want to be careful about how we do it and communicating it loudly. Anyone that has scripts making assumptions based on current argument behavior could be affected depending on the change and how they're using it.

**Comment by zalberico** [comment]
Changing this behavior would be a nice (easy?) win if we could get it into an upcoming release

**Comment by jalehman** [comment]
@zalberico It'll happen soon. @barter-simsum are you working on this? Or are we searching for a newer contributor to grab this one @vvisigoth?

**Comment by zalberico** [comment]
Bumping this one as it come up in UC: Help again. @jalehman can we get this in the next release?

**Comment by jalehman** [comment]
Short answer: Maybe. 

Long answer: @barter-simsum is on it just as soon as he finishes his work on the 8gb loom, which takes priority. Bandwidth for this will depend on what comes up in testing. Last we spoke about it he had seemed to think that this was a fairly straightforward solution, so I'm confident it'll happen soon.

**Comment by zalberico** [comment]
Cool, thanks!

**Comment by zalberico** [comment]
This already merged, but it’d be good to show usage on failure.

Often I’m trying to pack with loom 32 and get the arg order wrong and it starts trying to create a comet. An example on error of arg ordering would be good,  but this is still way better than creating a comet (thanks).
