### ISSUE TITLE
-Y option misnames resulting file

### ISSUE THREAD

**Issue by will-hanlen** [urbit/vere#222]
**Command:**
```
# from a docked fake ~zod
./.run -X /j/code/~zod -Y lus_code -Z p
```

**Expected behavior:**
Writes result of scry to `.urb/put/lus_code.txt`

**Actual behavior:**
Writes to `.urb/put/us_code.txt`

Note the first letter is missing.

I think it is caused by the `+ 1` in this line:

https://github.com/urbit/vere/blob/7098eb8825d96a2387795f643bdb2973d148a557/pkg/vere/pier.c#L520

I presume the `+ 1` is there to strip a leading `/` in the case where no `-Y` option is given, but in the case where it is given, the file is always misnamed.

**Comment by philipcmonk** [comment]
I ran into this the other day and was actually about to create an issue for this.  I've got a fix, which I'll PR right now.
