### ISSUE TITLE
fake-ship tests are not run under gc

### ISSUE THREAD

**Issue by joemfb** [urbit/vere#332]
This looks like a regression during demonorepofication.

**Comment by matthew-levan** [comment]
gc?

**Comment by joemfb** [comment]
Garbage collection. Build with `U3_MEMORY_DEBUG`, run (but not boot) with `-g`. This is essential for catching memory leaks early.

**Comment by matthew-levan** [comment]
Ok that's what I thought but didn't know about the association with
`U3_MEMORY_DEBUG`. Will get this done by EOW.

**Comment by matthew-levan** [comment]
Ok that's what I thought but didn't know about the association with `U3_MEMORY_DEBUG`. Will get this done by EOW.
