### ISSUE TITLE
click: input threads must not have comments in them

### ISSUE THREAD

**Issue by nick1udwig** [urbit/vere#344]
See the parsing of inline thread files that happens [on line 191](https://github.com/urbit/vere/blob/5eddeb07c0c2db42735f3251f4c6205c2e557b95/pkg/click/click#L191).

A reasonable solution would be to document the differences in parsing the inline thread from the standard Hoon parser (e.g. "comments will break it" and whatever else).

A better solution would be to modify the parsing to properly handle comments.

Another improvement might be the inclusion of an example of an inline thread file that will work.

**Comment by ashelkovnykov** [comment]
Going to move this to [urbit/tools](https://github.com/urbit/tools), which is the new home of click
