### ISSUE TITLE
`boot: snapshot too big for loom`

### ISSUE THREAD

**Issue by Demonstrandum** [urbit/vere#359]
Ship was working normally until I rebooted it, and now suddenly any thing I try to do is met by a
```
boot: snapshot too big for loom
```
error message.

I usually run with `--loom 32` but have tried with `33` as well.
I've been using the v2.1 (linux-aarch64) release without problems until now. I've also tried using the latest (https://github.com/urbit/vere/commit/54598bd8418d28abb4bbc2a80965c16a1248527e) v2.3 binary as well.

For example:

```console
nix% ./vere-v2.1-linux-aarch64 --loom 33 minten-migmug
~
urbit 2.1
boot: home is /srv/urbit/minten-migmug
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
loom: mapped 8192MB
boot: snapshot too big for loom
pier: serf unexpectedly shut down

nix% ./vere-v2.3-linux-aarch64 --loom 33 minten-migmug
~
urbit 2.3-54598bd
boot: home is /srv/urbit/minten-migmug
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
loom: mapped 8192MB
boot: snapshot too big for loom
pier: serf unexpectedly shut down

nix% ./vere-v2.3-linux-aarch64 meld minten-migmug --loom 33
loom: mapped 8192MB
boot: snapshot too big for loom
```

**Comment by joemfb** [comment]
How big is the snapshot? You can check with `ls -lh minten-migmug/.urb/chk`.

**Comment by Demonstrandum** [comment]
I've been checking with `du` and thought it was normal, but now I see that `ls` reports `south.bin` to be a ridiculous size:

```console
nix% du -h minten-migmug/.urb/chk/*
1.4G	minten-migmug/.urb/chk/north.bin
32K	minten-migmug/.urb/chk/south.bin
nix% ls -lh minten-migmug/.urb/chk
total 1.4G
-rw-r--r-- 1 samuel users 1.4G May  1 14:33 north.bin
-rw-r--r-- 1 samuel users  64T May  1 14:33 south.bin
nix% ls -l minten-migmug/.urb/chk
total 1443184
-rw-r--r-- 1 samuel users     1477787648 May  1 14:33 north.bin
-rw-r--r-- 1 samuel users 70366596710400 May  1 14:33 south.bin
nix%
```

so this might not be related to vere...

**Comment by Demonstrandum** [comment]
Likely some filesystem corruption, don't know what could have caused it.

Reading the file just spits out endless NULs after about `16384` bytes, so I ran `truncate -s 16K south.bin` and now everything seems to be working fine.

Sorry for the waste of time!
