### ISSUE TITLE
Migrate from Urbit monorepo

### ISSUE THREAD

**Issue by mcevoypeter** [urbit/vere#39]
## Pre-migration checklist
- [x] `linux-x86_64`: clean build
- [x] `linux-x86_64`: boot fake ship
- [x] `linux-x86_64`: boot comet
- [x] `macos-arm64`: clean build
- [x] `macos-arm64`: boot fake ship
- [x] `macos-arm64`: boot comet
- [x] `macos-x86_64`: clean build
- [x] `macos-x86_64`: boot fake ship
- [x] `macos-x86_64`: boot comet
- [x] Review and merge #21.
- [x] Perform a dummy release and ensure the resulting binaries work on all four supported platforms.
  - [x] `linux-x86_64`
  - [x] `macos-arm64`
  - [x] `macos-x86_64`
- [x] Grab any additional commits to `next/vere` in [urbit/urbit](https://github.com/urbit/urbit) that have landed since `71d06e544f7fe641ac0a9dad1fe07576761227ec`.
- [x] Review and update documentation to remove references to non-runtime work.
- [x] Prepare updates to binary links throughout urbit.org
- [ ] Complete final review of old build system to ensure all features have been ported over.

## Post-migration checklist
- [ ] Remove all runtime-related files and references in [urbit/urbit](https://github.com/urbit/urbit).
- [ ] Clearly communicate to runtime developers that they need to file an issue against this repo for anything that appears broken in the new repo.
- [ ] Collect list of open runtime-related PRs in [urbit/urbit](https://github.com/urbit/urbit) and re-open them in this repo.

**Comment by mcevoypeter** [comment]
Closing this since we've now successfully released out of this repo. Final cleanup is tracked by #125.

**Comment by ohAitch** [comment]
How hard would it be to port all relevantly tagged issues out of the monorepo, as happened the other way when the vere and arvo repos stopped being separate? ~~And how many years ETA on these ending up folded back together again?~~
