### ISSUE TITLE
make dbg config default build

### ISSUE THREAD

**Issue by barter-simsum** [urbit/vere#478]
very simple change, but let's wait for #469 to merge.

a non-optimized debug build should be the default since it's the one devs
specify most often. Release/fully optimized builds should be a special case.

i.e. 
bazel build :urbit ->
bazel build --compilation_mode=opt :urbit

bazel build --compilation_mode=dbg :urbit ->
bazel build :urbit

**Comment by joemfb** [comment]
i disagree, more people build urbit than debug with it, and the performance impact is pretty drastic. If you know how to debug, you're capable of deoptimizing ... ;)

**Comment by barter-simsum** [comment]
you're right, I need to attend my runtime unconscious bias training. I guess a
lot of people building from source are just doing it to run hoon.
