### ISSUE TITLE
Gracefully handle cases where `urbit roll` didn't complete successfully

### ISSUE THREAD

**Issue by matthew-levan** [urbit/vere#530]
This happened on @jalehman's ~siddef ship.

**Comment by joemfb** [comment]
@matthew-levan do you have any more details about how `roll` had failed, or what the subsequent error was?

**Comment by mopfel-winrux** [comment]
It was due to the docker version switching from 3.0 back to 2.12

**Comment by joemfb** [comment]
Ie, re-upgrade after downgrade will resolve the issue.

**Comment by matthew-levan** [comment]
Ok so we can close this after #531 gets reviewed and merged then.
