### ISSUE TITLE
Automatically create GitHub releases

### ISSUE THREAD

**Issue by matthew-levan** [urbit/vere#57]
Use the `gh` CLI to create a new GitHub release as part of the existing release flow in our CI code. GitHub releases should include:
* a compressed archive for each of our supported platforms, 
* release notes, 
* and a list of contributions/commits since last release.

**Comment by mcevoypeter** [comment]
It'd be great if we had a `.RELEASE_NOTES.md` file tracked in the root of the repo. When the releaser goes to release a new binary to the `live` channel by opening a PR to merge `release` into `master`, they'd update `.RELEASE_DESCRIPTION.md` to include a description of the release. Then, when that PR gets merged into `master` the "generate release notes" flow would auto generate the change log, create the tag, generate the binary tarballs, and insert the description from `.RELEASE_DESCRIPTION.md` into the release. As a result, all the releaser has to do is merge the PR, and the rest is taken care of.
