### ISSUE TITLE
Ships failing to start with "disk: unknown epoch version"

### ISSUE THREAD

**Issue by dosullivan** [urbit/vere#640]
We've seen a handful of ships on the Tlon Hosting platform have some issues with the new `chop` and `roll` setup. Sometimes the newest epoch doesn't have anything set inside its `epoc.txt` file; it's just an empty file. 

We first run `roll`, and then run `chop` as part of scheduled maintenance on a ship. 

In about ~10 ships now, when we run `roll`, the `epoc.txt` file in the latest epoch directory ends up with nothing written to it. The next time we try to start the ship, it crashes with this log, because the file is empty:
```
~
urbit 3.0
boot: home is /pier/<ship-name>
disk: unknown epoch version: '', expected '1'
upgrade runtime version
unable to open event log
```

If I go into `.urb/log` inside the pier and find the latest epoch, and then put in the `1` that vere is expecting, the ship then boots successfully.

**Comment by Tenari** [comment]
seems related: https://github.com/urbit/urbit/issues/6989
